### PR TITLE
calculator layout

### PR DESCRIPTION
**Pull request by Goldinium**
- Deleted all the boilerplate from Create React App (text, images, styles).
- Created a new directory called components.
- Inside components, created a new `Calculator.js` file.
- In `Calculator.js,` created a React component that matches the provided design
- Implemented the design only (JSX and CSS)
- Used functional components
- Created at least 1 child component
- Imported `Calculator.js` and used it in the top-level component: `App.js`
- Tested it in the browser; it renders without problems.

Thank you.

### CODE REVIEW

**Review by Efiamotu-1 — COMMENTED** [review]
Hi @Goldinium , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request
 

You have submitted a project, that is not following the proper `gitflow`, you are required to open a pull request from your dev branch not your main branch. so i kindly suggest you make this necessary change and resubmit for review.
- [ ] see this link on how to use proper [gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Goldinium** [comment]
> Hi @Goldinium ,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> ## Invalid Code Review Request
> 
>  [  ](https://user-images.githubusercontent.com/97100091/194103659-a0270409-def7-4972-b884-9f7c141eb90a.gif) [ ](https://user-images.githubusercontent.com/97100091/194103659-a0270409-def7-4972-b884-9f7c141eb90a.gif)
> 
> You have submitted a project, that is not following the proper `gitflow`, you are required to open a pull request from your dev branch not your main branch. so i kindly suggest you make this necessary change and resubmit for review.
> 
>     * [ ]  see this link on how to use proper [gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md)
> 
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

Hello,

This is not the main branch this is a dev branch, the main branch is `master`

**Review by Qoosim — COMMENTED** [review]
#  *Status: Invalid Request* :red_circle: 

Hi @Goldinium, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.



## Invalid Code Review Request

You have submitted a project, that does not follow correct `gitflow` as mentioned by the previous reviewer. Kindly follow correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Goldinium** [comment]
> # _Status: Invalid Request_ 🔴
> 
> Hi @Goldinium,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
>  [  ](https://user-images.githubusercontent.com/97100091/194103659-a0270409-def7-4972-b884-9f7c141eb90a.gif) [ ](https://user-images.githubusercontent.com/97100091/194103659-a0270409-def7-4972-b884-9f7c141eb90a.gif)
> ## Invalid Code Review Request
> 
> You have submitted a project, that does not follow correct `gitflow` as mentioned by the previous reviewer. Kindly follow correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md)
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

Did you read what I said above? This is not the main branch this is a dev branch, the main branch is `master`

**Review by Qoosim — COMMENTED** [review]
#  *Status: Invalid Request* :red_circle: 

Hi @Goldinium, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.



## Invalid Code Review Request

You have submitted a project, that does not follow the right workflow.
### Note:
You may need to go through this [link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) to refresh your memory on how to use gitflow. Let me briefly inform you how it works.

You're expected to create a branch called `dev`, make it default. Then create a feature-branch where all your works would be done. You will then open your PR from your feature-branch into the dev branch. This is how gitflow workflow works. I wish you the best understanding of this.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request closed without merging**
